language: php
dist: trusty

php:
  - 7.1

services:
 - mysql
 
before_install:
  - cp .env.testing .env
  - mysql -e 'CREATE DATABASE test;'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux 

install:
  - travis_retry composer install --no-interaction

before_script:
  - npm install
  - php artisan key:generate
  - php artisan migrate:refresh --seed
  - php artisan serve
 
script:
  - php artisan dusk
