language: php

php:
  - 7.0
  
services:
  - mysql
  
before_install:
  - mysql -u root -e "SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('')"
  
install:
  - mysql -e 'create database IF NOT EXISTS laravel_test;'
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.testing .env # Create a new .env file
  - php artisan key:generate # Generate application key
  - php artisan migrate:refresh --seed # Seed the database

before_script:
  - phantomjs --webdriver=127.0.0.1:9515 & # Start PhantomJS driver
  - php artisan serve & # Start server
  - sleep 5 # Give PhantomJS and Artisan time to start

script: 
  - php artisan dusk
